package com.trackolap;

public enum AlertType {
	IGNITION_ON, IGNITION_OFF, SPEED, GEO_FENCE, POWER_OFF, GEO_FENCE_IN, GEO_FENCE_OUT, LOW_BATTERY, SOS, COMMAND, AC_ON, AC_OFF,
	HARSH_BREAK, HARSH_ACC, NETWORK_DISCONNECTED
}
